import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>
      <main>
        <AppBar position="static">
          <Container maxWidth="xl">
            <Box></Box>
          </Container>
        </AppBar>
      </main>
    </>
  );
};
export default Home;
